// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHbVfHXJMinUye4yZsVKNUgkeymZ10L6c',
    appId: '1:882851110601:web:f0dc226e7a177492edf718',
    messagingSenderId: '882851110601',
    projectId: 'chatapp-6a221',
    authDomain: 'chatapp-6a221.firebaseapp.com',
    storageBucket: 'chatapp-6a221.appspot.com',
    measurementId: 'G-LSJLVDP4W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD86oXlI_5ItqZuTQ3uE6TsWcaBBywVEQk',
    appId: '1:882851110601:android:cc42039faef696b3edf718',
    messagingSenderId: '882851110601',
    projectId: 'chatapp-6a221',
    storageBucket: 'chatapp-6a221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLq_myDjF06EFfAGjSoxYaQfVdVXmrFN8',
    appId: '1:882851110601:ios:3fe22e6a6aee74a6edf718',
    messagingSenderId: '882851110601',
    projectId: 'chatapp-6a221',
    storageBucket: 'chatapp-6a221.appspot.com',
    androidClientId: '882851110601-igk01nhdkd85vkvbhno36hhuq0i1ckrg.apps.googleusercontent.com',
    iosClientId: '882851110601-1gpbvpp76ii3ptqgqersbkgq1qbrh04q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLq_myDjF06EFfAGjSoxYaQfVdVXmrFN8',
    appId: '1:882851110601:ios:82c4cdac96d0a4c1edf718',
    messagingSenderId: '882851110601',
    projectId: 'chatapp-6a221',
    storageBucket: 'chatapp-6a221.appspot.com',
    androidClientId: '882851110601-igk01nhdkd85vkvbhno36hhuq0i1ckrg.apps.googleusercontent.com',
    iosClientId: '882851110601-16m1ub366elm99m1fr0296lim1f0165i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
